import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { La_Belle_Aurore as FontHandwritting, Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontHandwritting = FontHandwritting({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-handwritting",
});

const MonaLisa = localFont({
  src: "@/assets/fonts/MonoLisa-regular.ttf",
  variable: "--font-monalisa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-bg-default font-sans antialiased",
          fontSans.variable,
          fontHandwritting.variable,
          MonaLisa.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
